# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cddca05e44bd05f9c11a640b48f31c5ea14ca8897c42e35d4d78ea99c50aabc2101a831d10ad6470d185418b7d4d8b8733c74f6cf53a69ce838dcf269016ed37

test:
  secret_key_base: a08ecc067f82d45f9c64292349fdf8189f548bd03fe57793583b39d61f7279a9e9402382a58d1d1baa28658971300fec0d32aa113e45aaaada25a66325895157

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
